#!/bin/bash
# Function definitions used in the entrypoint file.

. /base/functions


#
# execute actual backup
#
function do_dump() {
  # what is the name of our source and target?
  now=$(date -u +"%Y-%m-%d_%H-%M-%S")
  # SOURCE: file that the uploader looks for when performing the upload
  # TARGET: the remote file that is actually uploaded

  # option to replace
  if [ -n "$DB_DUMP_SAFECHARS" ]; then
    now=${now//:/-}
  fi
  SOURCE=${SOURCE_PREFIX}_${now}.$EXTENSION
  TARGET=${SOURCE}

  curl -i -X POST http://$DB_SERVER:9000/api/backup -H "X-API-Key: $DB_PASS" -H 'Content-Type: application/json' --data '{}' --output ${TMPDIR}/${SOURCE}
  [ $? -ne 0 ] && return 1

  return 0
}
